### PR TITLE
optimization for associative reductions

### PR DESCRIPTION
**Pull request by Alexander-Barth**
This PR addresses https://github.com/meggart/DiskArrays.jl/issues/188

### CODE REVIEW

**Comment by rafaqz** [comment]
I think we also need the version with a function as first argument.

And also is count really in that list? Especially with the function? I thought it would need some tweaking.

**Comment by rafaqz** [comment]
Oh right the dispatch on internals may have broken, sorry I should have realised that. We also just switched this to the main method in DimensionalData.jl

https://github.com/meggart/DiskArrays.jl/blob/ccd3092ca6f32c2663ded1d74176aa9dd222a5ef/src/mapreduce.jl#L7-L12

**Comment by meggart** [comment]
> But probably we can keep the tests to catch these things in future, especially if we explicitly test the access count of those arrays after the reductions, to make sure we are not hitting fallbacks. We clearely are not doing that at the moment.

I am not sure about this we have these tests: https://github.com/meggart/DiskArrays.jl/blob/ccd3092ca6f32c2663ded1d74176aa9dd222a5ef/test/runtests.jl#L114 which also test the access count. Also the test that was added in this PR already passes the access_count test on the current main:

````julia
using DiskArrays
using DiskArrays.TestTypes
using Test
A = rand(1:10,30,30)
DA = AccessCountDiskArray(A,chunksize=(2,2));

r = sum(DA);

@test getindex_count(DA)==length(eachchunk(DA))
````

Here we test that every chunk is accessed exactly once, please try this on main, so I would guess the slow performance in #188 must come from somewhere else or some operation we are not yet hitting with our tests.

**Comment by meggart** [comment]
Ok, I did some digging and realized that currently we do not hit our mapreduce methods but rather the iterator fallback, which does read the data chunk by chunk but is more inefficient and numerically unstable compared to this implementation. Will launch Cthulhu to find out where this goes wrong

**Comment by rafaqz** [comment]
Seems this has been pretty productive! good to have all those things working and tested.

I think youre right - `sum`, `prod`, `any` and `all` are the real beneficiaries of not using `mapreduce`.  `maximum` and `minimum` are probably worth keeping too for reliability.


I don't quite understand how `count` is working over chunks here because it returns an `Int` but does not work on an iterator of `Int`. I thought it would need to be `sum` as the outer function and `count` as the inner.

**Comment by meggart** [comment]
Superseded by #196

**Pull request closed without merging**
